-- 문제 1번 
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", TO_CHAR(ENTRANCE_DATE, 'RRRR-MM-DD') "입학년도" 
FROM TB_STUDENT ts 
LEFT JOIN TB_DEPARTMENT td ON(ts.DEPARTMENT_NO = td.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '영어영문학과';

-- 문제 2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR tp
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 문제 3번
SELECT PROFESSOR_NAME "교수이름", 
FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE('19' || SUBSTR(PROFESSOR_SSN, 1, 2),'YYYY'))/12) "나이" 
FROM TB_PROFESSOR tp
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;

-- 문제 4번
SELECT SUBSTR(PROFESSOR_NAME, 2, LENGTH(PROFESSOR_NAME)-1 )"이름"
FROM TB_PROFESSOR tp;

-- 문제 5번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6), 'RRMMDD')) > 19;

-- 문제 6번
SELECT TO_CHAR(TO_DATE('2020-12-25'), 'DAY') "2020년 크리스마스 요일" FROM DUAL;

-- 문제 7번
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'), 'YYYY/MM/DD ') "첫번째",
TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'), 'YYYY/MM/DD ') "두번째" ,
TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY/MM/DD ') "세번째",
TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY/MM/DD ') "네번째"
FROM DUAL;

-- 문제 8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

-- 문제 9번
SELECT ROUND(AVG(POINT), 1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 문제 10번
SELECT DEPARTMENT_NO "학과번호", COUNT(*) "학생 수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 학과번호;

-- 문제 11번
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 문제 12번
SELECT TERM_NO, POINT
FROM TB_GRADE 
WHERE STUDENT_NO = 'A112113';

SELECT SUBSTR(TERM_NO, 1, 4) "년도", ROUND(AVG(POINT), 1) "년도 별 평점"
FROM TB_GRADE 
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 년도;

-- 문제 13번 : 학과별 휴학생수 파악
SELECT DEPARTMENT_NO "학과코드명"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 1;

SELECT DEPARTMENT_NO "학과코드명", COUNT(DECODE(ABSENCE_YN, 'Y', 1, 'N', NULL)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

SELECT DEPARTMENT_NO "학과코드명", SUM(DECODE(ABSENCE_YN, 'Y', 1, 'N', 0)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- 문제 14번
