-- 문제 1
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY 1 ;

-- 문제 2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 DESC;

-- 문제 3
SELECT STUDENT_NAME "학생이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT ts
WHERE STUDENT_NO LIKE '9%'
AND (STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '경기도%')
ORDER BY 1;

-- 문제 4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR tp 
JOIN TB_DEPARTMENT td ON (tp.DEPARTMENT_NO = td.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY 2;

-- 문제 5
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = '200402'
AND CLASS_NO = 'C3118100'
ORDER BY 2 DESC, 1;

-- 문제 6 WORD 참조
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT td ON(ts.DEPARTMENT_NO = td.DEPARTMENT_NO)
ORDER BY 2;

-- 문제 7
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS tc
JOIN TB_DEPARTMENT td ON(tc.DEPARTMENT_NO = td.DEPARTMENT_NO);

-- 문제 8 WORD 참조
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR tcp 
JOIN TB_CLASS tc ON(tcp.CLASS_NO = tc.CLASS_NO)
JOIN TB_PROFESSOR tp ON(tcp.PROFESSOR_NO = tp.PROFESSOR_NO);

-- 문제 9 WORD 참조
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR tcp 
JOIN TB_CLASS tc ON(tcp.CLASS_NO = tc.CLASS_NO)
JOIN TB_PROFESSOR tp ON(tcp.PROFESSOR_NO = tp.PROFESSOR_NO)
JOIN TB_DEPARTMENT td ON(tc.DEPARTMENT_NO = td.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

-- 문제 10
SELECT tg.STUDENT_NO "학번", STUDENT_NAME "학생 이름", ROUND(AVG(POINT), 1) "전체 평점"
FROM TB_GRADE tg 
JOIN TB_STUDENT ts ON(tg.STUDENT_NO = ts.STUDENT_NO)
JOIN TB_DEPARTMENT td ON(ts.DEPARTMENT_NO = td.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY tg.STUDENT_NO, STUDENT_NAME
ORDER BY 1;

-- 문제 11
SELECT DEPARTMENT_NAME "학과이름", STUDENT_NAME "학생이름", PROFESSOR_NAME "지도교수이름"
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT td ON(ts.DEPARTMENT_NO = td.DEPARTMENT_NO)
JOIN TB_PROFESSOR tp ON(ts.COACH_PROFESSOR_NO = tp.PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

-- 문제 12
SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_GRADE tg 
JOIN TB_CLASS tc ON(tg.CLASS_NO = tc.CLASS_NO)
JOIN TB_STUDENT ts ON(tg.STUDENT_NO = ts.STUDENT_NO)
WHERE TERM_NO LIKE '2007%'
AND CLASS_NAME = '인간관계론';

-- 문제 13
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS tc 
JOIN TB_DEPARTMENT td ON (tc.DEPARTMENT_NO = td.DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR tcp ON(tc.CLASS_NO = tcp.CLASS_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;

-- 문제 14
SELECT STUDENT_NAME "학생이름", NVL(PROFESSOR_NAME, '지도교수 미지정') "지도교수"
FROM TB_STUDENT ts 
LEFT JOIN TB_PROFESSOR tp ON(ts.COACH_PROFESSOR_NO = tp.PROFESSOR_NO)
JOIN TB_DEPARTMENT td ON(ts.DEPARTMENT_NO = td.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;

-- 문제 15
SELECT ts.STUDENT_NO "학번", ts.STUDENT_NAME "이름", td.DEPARTMENT_NAME "학과 이름", AVG(POINT)
FROM TB_STUDENT ts
JOIN TB_DEPARTMENT td ON(ts.DEPARTMENT_NO = td.DEPARTMENT_NO)
JOIN TB_GRADE tg ON(ts.STUDENT_NO = tg.STUDENT_NO)
WHERE ABSENCE_YN != 'Y'
GROUP BY ts.STUDENT_NO, ts.STUDENT_NAME, td.DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY 1;

-- 문제 16
SELECT tc.CLASS_NO, CLASS_NAME, AVG(POINT)
FROM TB_CLASS tc 
JOIN TB_DEPARTMENT td ON(tc.DEPARTMENT_NO = td.DEPARTMENT_NO)
JOIN TB_GRADE tg ON(tc.CLASS_NO = tg.CLASS_NO)
WHERE CLASS_TYPE LIKE '전공%'
AND DEPARTMENT_NAME = '환경조경학과'
GROUP BY tc.CLASS_NO, CLASS_NAME
ORDER BY 1;

-- 문제 17
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME = '최경희');

-- 문제 18
SELECT STUDENT_NO, STUDENT_NAME
FROM(
	SELECT ts.STUDENT_NO, STUDENT_NAME, AVG(POINT) 
	FROM TB_STUDENT ts 
	JOIN TB_DEPARTMENT td ON(ts.DEPARTMENT_NO = td.DEPARTMENT_NO)
	JOIN TB_GRADE tg ON(ts.STUDENT_NO = tg.STUDENT_NO)
	WHERE DEPARTMENT_NAME = '국어국문학과'
	GROUP BY ts.STUDENT_NO, STUDENT_NAME
	ORDER BY 3 DESC)
WHERE ROWNUM =1;

-- 문제 19
SELECT DEPARTMENT_NAME "계열학과명", ROUND(AVG(POINT), 1) "전공평점"
FROM TB_DEPARTMENT td
JOIN TB_CLASS tc ON(td.DEPARTMENT_NO = tc.DEPARTMENT_NO)
JOIN TB_GRADE tg ON(tc.CLASS_NO = tg.CLASS_NO)
WHERE CATEGORY = (SELECT CATEGORY FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '환경조경학과')
AND CLASS_TYPE LIKE '전공%'
GROUP BY DEPARTMENT_NAME
ORDER BY 1;


















